# config.py
import os

# Bot Configuration
BOT_TOKEN = os.getenv("BOT_TOKEN") or "YOUR_BOT_TOKEN"
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY") or "YOUR_GEMINI_API_KEY"
OWNER_USER_ID = int(os.getenv("OWNER_USER_ID", "123456789"))
PORT = int(os.getenv("PORT", 10000))

# File Size Limits
MAX_PDF_SIZE_MB = 15
MAX_IMAGE_SIZE_MB = 5
MAX_IMAGES = 10
PROCESSING_TIMEOUT = 300

# Gemini Models
GEMINI_MODELS = [
    "gemini-2.5-pro",
    "gemini-2.5-flash", 
    "gemini-2.5-flash-lite",
    "gemini-2.0-flash",
    "gemini-2.0-flash-001",
    "gemini-2.0-flash-lite",
    "gemini-2.0-flash-lite-001",
]

# Supported Languages
SUPPORTED_LANGUAGES = {
    "english": "English",
    "hindi": "Hindi", 
    "gujarati": "Gujarati"
}

# Supported Image Formats
SUPPORTED_IMAGE_TYPES = [
    ".jpg", ".jpeg", ".png", ".webp", 
    ".bmp", ".tiff", ".tif", ".heic", ".heif"
]

# AI Signature
STYLISH_SIGNATURE = "📚 Generated by QuickPYQ AI @TJPATELYT"